# Generated by Django 4.1.3 on 2022-12-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_description',
            field=models.TextField(max_length=2000),
        ),
    ]
